### ISSUE TITLE
Second anyfin doesn't work

### ISSUE THREAD

**Issue by wisethug** [ericBG/AnyfinCalculator#3] opened 2016-03-19 16:57 UTC
Hello ericBG ! 

The plugin is very good. However the second anyfin doesn't work when it comes down to telling how much dmg I have !

Any way to fix this ? 

Thanks

**Comment by ericBG** [comment] 2016-03-19 22:21
As far as I know I fixed this issue in version 1.0.1, could you just please check whether you are using that version?

Thank you!

**Comment by wisethug** [comment] 2016-03-20 10:10
The last one on the releases page. :(

**Comment by ericBG** [comment] 2016-03-20 11:23
That's 1.0.0, try [v1.0.1](https://github.com/ericBG/AnyfinCalculator/releases/tag/v1.0.1).

**Comment by wisethug** [comment] 2016-03-20 11:35
Hm, downloaded it, and in HS deck tracker the version displayerd is "1.0.0". Same bug happens :/

**Comment by ericBG** [comment] 2016-03-20 11:36
Turns out that's just me being lazy, and not editing the version string (sorry). Would you be able to post what's on the HDT log? I can't reproduce this...

**Comment by ericBG** [comment] 2016-04-01 15:03
Should be fixed with the new version.

**Closed as completed by ericBG** 2016-04-01 15:03 UTC
Labels: bug, can't repro
